"""
Django settings for CarnivoreIDApp project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import logging
import os
from pathlib import Path

from .log import setup_logging

SHARED_DATA_PATH = os.environ["SHARED_DATA_PATH"]
PRIVATE_DATA_PATH = os.environ["PRIVATE_DATA_PATH"]

setup_logging()
logger = logging.getLogger("app")
logger.info("Logger is set up.")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# env = environ.FileAwareEnv(
#     DEBUG=(bool, True)
# )
# environ.Env.read_env()

# WEBAPP_DATA = Path(SHARED_DATA_PATH) / "caidapp_data"  # BASE_DIR / "../caidapp_data"
# WEBAPP_DATA.mkdir(exist_ok=True, parents=True)

scpath = Path(PRIVATE_DATA_PATH) / "secretkey.txt"
if scpath.exists():
    with open(scpath, "r") as f:
        SECRET_KEY = f.read().strip()
else:
    logger.info("Secret key not found in 'secretkey.txt' generating new one.")
    with open(scpath, "w") as f:
        from django.core.management.utils import get_random_secret_key

        SECRET_KEY = f.write(get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)
if isinstance(DEBUG, str):
    DEBUG = DEBUG.lower() == "true"
logger.info(f"Setting environment variable {DEBUG=}.")

# A list of strings representing the host/domain names that this Django site can serve
CAID_HOST = os.getenv("CAID_HOST", default="localhost")
ALLOWED_HOSTS = [
    "127.0.0.1",
    ".localhost",  # '.' allows to match both 'www.localhost' and 'localhost'
    "147.228.43.21",
    ".caid.kky.zcu.cz",
    CAID_HOST,
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "caidapp.apps.CaidappConfig",
    # 'django.contrib.sites',
    "allauth",  # <--
    "allauth.account",  # <--
    "allauth.socialaccount",  # <--
    "allauth.socialaccount.providers.google",  # <--
    "widget_tweaks"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CarnivoreIDApp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CarnivoreIDApp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(PRIVATE_DATA_PATH) / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"
TIME_ZONE = "Europe/Prague"
CELERY_TIMEZONE = "Europe/Prague"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(SHARED_DATA_PATH) / "media"
# use python manage.py collectstatic
STATIC_ROOT = Path(SHARED_DATA_PATH) / "static"
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
#     "/api_static/",
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CREDS_JSON_FILE = Path(PRIVATE_DATA_PATH) / "piglegsurgery-creds.json"

LOGIN_REDIRECT_URL = "/caidapp/uploads"

SOCIALACCOUNT_LOGIN_ON_GET = True

ACCOUNT_DEFAULT_HTTP_PROTOCOL = os.environ.get("ACCOUNT_DEFAULT_HTTP_PROTOCOL", default="https")
