"""
Django settings for CarnivoreIDApp project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import logging
import sentry_sdk
import os
from pathlib import Path

from .log import setup_logging

SHARED_DATA_PATH = os.environ["SHARED_DATA_PATH"]
PRIVATE_DATA_PATH = os.environ["PRIVATE_DATA_PATH"]

POSTGRES_DB = os.environ["POSTGRES_DB"]
POSTGRES_HOST = os.environ["POSTGRES_HOST"]
POSTGRES_PORT = os.environ["POSTGRES_PORT"]
POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_PASS = os.environ["POSTGRES_PASS"]

ALLAUTH_GOOGLE_CLIENT_ID = os.getenv("ALLAUTH_GOOGLE_CLIENT_ID", default="")
ALLAUTH_GOOGLE_CLIENT_SECRET = os.getenv("ALLAUTH_GOOGLE_CLIENT_SECRET", default="")

setup_logging()
logger = logging.getLogger("app")
logger.info("Logger is set up.")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

scpath = Path(PRIVATE_DATA_PATH) / "secretkey.txt"
if scpath.exists():
    with open(scpath, "r") as f:
        SECRET_KEY = f.read().strip()
else:
    logger.info("Secret key not found in 'secretkey.txt' generating new one.")
    with open(scpath, "w") as f:
        from django.core.management.utils import get_random_secret_key

        SECRET_KEY = f.write(get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)
if isinstance(DEBUG, str):
    DEBUG = DEBUG.lower() == "true"
logger.info(f"Setting environment variable {DEBUG=}.")

# DEBUG_TOOLBAR = DEBUG
DEBUG_TOOLBAR = False

# A list of strings representing the host/domain names that this Django site can serve
CAID_HOST = os.getenv("CAID_ALLOWED_HOSTS", default="")
ALLOWED_HOSTS = [
    "127.0.0.1",
    ".localhost",  # '.' allows to match both 'www.localhost' and 'localhost'
    "147.228.43.21",
    # ".caid.kky.zcu.cz",
    # ".kky.zcu.cz",
]
ALLOWED_HOSTS.extend(CAID_HOST.split(","))

CAID_CSRF_TRUSTED_ORIGINS=os.getenv("CSRF_TRUSTED_ORIGINS", default="")
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'http://localhost',
    'http://localhost:13680',
    'http://127.0.0.1:13680'
    # 'http://caid.kky.zcu.cz:13680',
    # 'https://caid.kky.zcu.cz:13680',
    # 'https://localhost:13680',

]
CSRF_TRUSTED_ORIGINS.extend(CAID_CSRF_TRUSTED_ORIGINS.split(","))
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "caidapp.apps.CaidappConfig",
    "allauth",  # <--
    "allauth.account",  # <--
    "allauth.socialaccount",  # <--
    "allauth.socialaccount.providers.google",  # <--
    "widget_tweaks",
    "location_field.apps.DefaultConfig",
    "django.db.migrations",
    'djangoaddicts.pygwalker',
    'handyhelpers',
    "compressor",
    "django_filters",
    # "debug_toolbar"
    # 'pagination',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
    "caidapp.middleware.ImpersonateMiddleware",
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# COMPRESS_ENABLED = True  # aktivuje kompresi i v debug režimu (obvykle jen v produkci)
# COMPRESS_OUTPUT_DIR = 'CACHE'  # kam se uloží zkomprimované soubory

if DEBUG_TOOLBAR:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]


ROOT_URLCONF = "CarnivoreIDApp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CarnivoreIDApp.wsgi.application"

LOCATION_FIELD = {
    "map.provider": "openstreetmap",
    "search.provider": "nominatim",
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRES_DB,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASS,
        "HOST": POSTGRES_HOST,
        "PORT": POSTGRES_PORT,
        # "OPTIONS": {
        #     "service": "my_service",
        # },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Prague"
CELERY_TIMEZONE = "Europe/Prague"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(SHARED_DATA_PATH) / "media"
# use python manage.py collectstatic
STATIC_ROOT = Path(SHARED_DATA_PATH) / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CREDS_JSON_FILE = Path(PRIVATE_DATA_PATH) / "piglegsurgery-creds.json"

LOGIN_REDIRECT_URL = "/caidapp/uploads"

SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": ALLAUTH_GOOGLE_CLIENT_ID,
            "secret": ALLAUTH_GOOGLE_CLIENT_SECRET,
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

ACCOUNT_DEFAULT_HTTP_PROTOCOL = os.environ.get("ACCOUNT_DEFAULT_HTTP_PROTOCOL", default="https")

# if the automatic identification is under the threshold, add it to the list for manual confirmation
IDENTITY_MANUAL_CONFIRMATION_THRESHOLD = 20.0

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    "localhost"
    # ...
]
def show_toolbar(request):
    if DEBUG:
        return True

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': show_toolbar,
}

SENTRY_DSN = os.getenv("SENTRY_DSN", default=None)

if SENTRY_DSN:

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        _experiments={
            # Set continuous_profiling_auto_start to True
            # to automatically start the profiler on when
            # possible.
            "continuous_profiling_auto_start": True,
        },
    )