FROM nvcr.io/nvidia/pytorch:23.05-py3

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    git \
    ffmpeg \
    libsm6 \
    libxext6 \
    tesseract-ocr \
    exiftool \
    libwebp-dev \
 && rm -rf /var/lib/apt/lists/*
