# Generated by Django 3.2.18 on 2024-01-22 14:37

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0028_location_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location",
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
