# Generated by Django 3.2.18 on 2023-05-19 12:22

import datetime

import caidapp.model_tools
import caidapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CIDUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "hash",
                    models.CharField(default=caidapp.model_tools.random_string12, max_length=50),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=datetime.datetime.now, verbose_name="Uploaded at"),
                ),
                (
                    "archivefile",
                    models.FileField(
                        max_length=500,
                        upload_to=caidapp.model_tools.get_zip_path_in_unique_folder,
                        verbose_name="Archive File",
                    ),
                ),
                ("preview", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "outputdir",
                    models.CharField(
                        blank=True,
                        default=caidapp.model_tools.get_output_dir,
                        max_length=255,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to=models.CharField(
                            blank=True,
                            default=caidapp.model_tools.get_output_dir,
                            max_length=255,
                        ),
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=models.CharField(
                            blank=True,
                            default=caidapp.model_tools.get_output_dir,
                            max_length=255,
                        ),
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=models.CharField(
                            blank=True,
                            default=caidapp.model_tools.get_output_dir,
                            max_length=255,
                        ),
                    ),
                ),
                (
                    "hash",
                    models.CharField(blank=True, default=caidapp.models.get_hash, max_length=255),
                ),
                (
                    "status",
                    models.CharField(blank=True, default="Created", max_length=255),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Finished at"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caidapp.ciduser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mediafile",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="",
                        verbose_name="Media File",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caidapp.uploadedarchive",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caidapp.taxon",
                    ),
                ),
            ],
        ),
    ]
