# Generated by Django 3.2.18 on 2023-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
