# Generated by Django 3.2.18 on 2023-05-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0002_taxon_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxon",
            name="hash",
        ),
    ]
