# Generated by Django 3.2.18 on 2023-06-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0004_auto_20230601_1014"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediafile",
            old_name="species",
            new_name="category",
        ),
    ]
