# Generated by Django 3.2.18 on 2023-06-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0005_rename_species_mediafile_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedarchive",
            name="location_at_upload",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
