# Generated by Django 3.2.18 on 2023-06-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0006_uploadedarchive_location_at_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="captured_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Captured at"),
        ),
    ]
