# Generated by Django 3.2.18 on 2023-07-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0007_mediafile_captured_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="thumbnail",
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=""),
        ),
    ]
