# Generated by Django 3.2.18 on 2023-07-16 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0008_mediafile_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="caidapp.uploadedarchive"
            ),
        ),
    ]
