# Generated by Django 3.2.18 on 2023-08-28 12:22

import caidapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0010_album_albumsharerole_albumshareroletype"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="public_hash",
            field=models.CharField(blank=True, default=caidapp.models.get_hash, max_length=255),
        ),
    ]
