# Generated by Django 3.2.18 on 2023-08-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0011_album_public_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cover",
                to="caidapp.mediafile",
            ),
        ),
    ]
