# Generated by Django 3.2.18 on 2023-09-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0012_album_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="album",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover",
                to="caidapp.mediafile",
            ),
        ),
        migrations.CreateModel(
            name="MediafilesForIdentification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top1score", models.FloatField(blank=True, null=True)),
                ("top2score", models.FloatField(blank=True, null=True)),
                ("top3score", models.FloatField(blank=True, null=True)),
                ("top1name", models.CharField(blank=True, default="", max_length=255)),
                ("top2name", models.CharField(blank=True, default="", max_length=255)),
                ("top3name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "mediafile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caidapp.mediafile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mediafile",
            name="indentity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.individualidentity",
            ),
        ),
    ]
