# Generated by Django 3.2.18 on 2023-09-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0013_auto_20230901_0916"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafilesforidentification",
            name="top1mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top1",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="mediafilesforidentification",
            name="top2mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top2",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="mediafilesforidentification",
            name="top3mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top3",
                to="caidapp.mediafile",
            ),
        ),
    ]
