# Generated by Django 3.2.18 on 2023-09-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0014_auto_20230901_0918"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="ciduser",
            name="workgroup_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ciduser",
            name="workgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.workgroup",
            ),
        ),
    ]
