# Generated by Django 3.2.18 on 2023-09-08 12:59

import caidapp.model_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0015_auto_20230907_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="hash",
            field=models.CharField(default=caidapp.model_tools.randomString12, max_length=50),
        ),
    ]
