# Generated by Django 3.2.18 on 2023-09-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0016_workgroup_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualidentity",
            name="id_worker",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="individualidentity",
            name="owner_workgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.workgroup",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="identity_is_representative",
            field=models.BooleanField(default=False),
        ),
    ]
