# Generated by Django 3.2.18 on 2023-09-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0017_auto_20230911_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualidentity",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.ciduser",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.ciduser",
            ),
        ),
        migrations.AddField(
            model_name="uploadedarchive",
            name="contains_identities",
            field=models.BooleanField(default=False),
        ),
    ]
