# Generated by Django 3.2.18 on 2023-09-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0018_auto_20230918_1421"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediafile",
            old_name="indentity",
            new_name="identity",
        ),
    ]
