# Generated by Django 3.2.18 on 2023-09-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0019_rename_indentity_mediafile_identity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediafile",
            options={"ordering": ["-identity_is_representative", "captured_at"]},
        ),
    ]
