# Generated by Django 3.2.18 on 2023-10-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0020_alter_mediafile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedarchive",
            name="contains_single_taxon",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.individualidentity",
            ),
        ),
    ]
