# Generated by Django 3.2.18 on 2023-10-26 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0021_auto_20231013_1354"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top1mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top1",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top2mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top2",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top3mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top3",
                to="caidapp.mediafile",
            ),
        ),
    ]
