# Generated by Django 3.2.18 on 2023-11-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0022_auto_20231026_1931"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedarchive",
            name="contains_single_taxon",
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.individualidentity",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top1mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top1",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top2mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top2",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top3mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top3",
                to="caidapp.mediafile",
            ),
        ),
    ]
