# Generated by Django 3.2.18 on 2023-11-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0024_auto_20231102_2151"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediafile",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="uploadedarchive",
            name="identification_finished_at",
        ),
        migrations.RemoveField(
            model_name="uploadedarchive",
            name="identification_started_at",
        ),
        migrations.RemoveField(
            model_name="uploadedarchive",
            name="identification_status",
        ),
        migrations.RemoveField(
            model_name="uploadedarchive",
            name="output_updated_at",
        ),
        migrations.AddField(
            model_name="uploadedarchive",
            name="contains_single_taxon",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.individualidentity",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top1mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top1",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top2mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top2",
                to="caidapp.mediafile",
            ),
        ),
        migrations.AlterField(
            model_name="mediafilesforidentification",
            name="top3mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top3",
                to="caidapp.mediafile",
            ),
        ),
    ]
