# Generated by Django 3.2.18 on 2023-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0025_auto_20231106_0936"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="identification_init_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Identification init at"
            ),
        ),
        migrations.AddField(
            model_name="workgroup",
            name="identification_init_status",
            field=models.CharField(blank=True, default="Not initiated", max_length=255),
        ),
    ]
