# Generated by Django 3.2.18 on 2023-12-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0026_auto_20231129_1852"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="uploadedarchive",
            name="identification_finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Finished at"),
        ),
        migrations.AddField(
            model_name="uploadedarchive",
            name="identification_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Started at"),
        ),
        migrations.AddField(
            model_name="uploadedarchive",
            name="identification_status",
            field=models.CharField(blank=True, default="Created", max_length=255),
        ),
        migrations.AddField(
            model_name="uploadedarchive",
            name="output_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Output updated at"),
        ),
    ]
