# Generated by Django 3.2.18 on 2024-01-22 15:07

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0027_auto_20231208_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                blank=True, max_length=63, null=True
            ),
        ),
    ]
