# Generated by Django 3.2.18 on 2024-01-22 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0028_location_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.ciduser",
            ),
        ),
    ]
