# Generated by Django 3.2.18 on 2024-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0029_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='identification_init_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
