# Generated by Django 3.2.18 on 2024-02-21 13:23

import datetime

import caidapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0030_workgroup_identification_init_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "created_at",
                    models.DateTimeField(default=datetime.datetime.now, verbose_name="Created at"),
                ),
                (
                    "hash",
                    models.CharField(blank=True, default=caidapp.models._hash, max_length=255),
                ),
                (
                    "archives",
                    models.ManyToManyField(blank=True, to="caidapp.UploadedArchive"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caidapp.ciduser",
                    ),
                ),
            ],
        ),
    ]
