# Generated by Django 3.2.18 on 2024-03-15 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("caidapp", "0031_archivecollection"),
    ]

    operations = [migrations.RenameModel("CIDUser", "CaIDUser")]
