# Generated by Django 3.2.18 on 2024-03-15 13:53

import caidapp.model_tools
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("caidapp", "0031_archivecollection"),
    ]

    operations = [
        migrations.RenameModel("CIDUser", "CaIDUser")
        # migrations.CreateModel(
        #     name='CaIDUser',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('hash', models.CharField(default=caidapp.model_tools.random_string12, max_length=50)),
        #         ('workgroup_admin', models.BooleanField(default=False)),
        #         ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #         ('workgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.workgroup')),
        #     ],
        # ),
        # migrations.AlterField(
        #     model_name='album',
        #     name='owner',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.caiduser'),
        # ),
        # migrations.AlterField(
        #     model_name='albumsharerole',
        #     name='user',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.caiduser'),
        # ),
        # migrations.AlterField(
        #     model_name='archivecollection',
        #     name='owner',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.caiduser'),
        # ),
        # migrations.AlterField(
        #     model_name='individualidentity',
        #     name='updated_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.caiduser'),
        # ),
        # migrations.AlterField(
        #     model_name='location',
        #     name='owner',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.caiduser'),
        # ),
        # migrations.AlterField(
        #     model_name='mediafile',
        #     name='updated_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.caiduser'),
        # ),
        # migrations.AlterField(
        #     model_name='uploadedarchive',
        #     name='owner',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.caiduser'),
        # ),
        # migrations.DeleteModel(
        #     name='CIDUser',
        # ),
    ]
