# Generated by Django 3.2.18 on 2024-03-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0032_auto_20240315_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='metadata_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnimalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('mediafile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.mediafile')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.taxon')),
            ],
        ),
    ]
