# Generated by Django 3.2.18 on 2024-03-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0033_auto_20240318_2002"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="image_file",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to="", verbose_name="Image File"),
        ),
    ]
