# Generated by Django 3.2.18 on 2024-03-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0035_uploadedarchive_taxon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedarchive',
            name='taxon',
        ),
        migrations.AddField(
            model_name='uploadedarchive',
            name='taxon_for_identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caidapp.taxon'),
        ),
    ]
