# Generated by Django 3.2.18 on 2024-03-18 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0036_auto_20240318_2212"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalobservation",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="animalobservation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.caiduser",
            ),
        ),
        migrations.AlterField(
            model_name="animalobservation",
            name="taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.taxon",
            ),
        ),
    ]
