# Generated by Django 3.2.18 on 2024-03-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0037_auto_20240318_2223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.caiduser",
            ),
        ),
    ]
