# Generated by Django 3.2.18 on 2024-03-18 22:05

import caidapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0038_alter_mediafile_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='visible_name',
            field=models.CharField(blank=True, default=caidapp.models.human_readable_hash, max_length=255),
        ),
    ]
