# Generated by Django 3.2.18 on 2024-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0039_location_visible_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='animal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
