# Generated by Django 3.2.18 on 2024-03-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0041_auto_20240320_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedarchive",
            name="location_at_upload_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.location",
            ),
        ),
    ]
