# Generated by Django 3.2.18 on 2024-03-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0042_uploadedarchive_location_at_upload_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(blank=True, default='image', max_length=255),
        ),
    ]
