# Generated by Django 3.2.18 on 2024-04-12 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0043_mediafile_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caidapp.caiduser'),
        ),
    ]
