# Generated by Django 3.2.18 on 2024-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0044_alter_location_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="caiduser",
            name="dir_import_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="caiduser",
            name="dir_import_status",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
