# Generated by Django 3.2.18 on 2024-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0045_auto_20240415_1107"),
    ]

    operations = [
        migrations.AddField(
            model_name="caiduser",
            name="import_dir",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
