# Generated by Django 3.2.18 on 2024-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0046_caiduser_import_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarchive',
            name='mediafiles_imported',
            field=models.BooleanField(default=False, verbose_name='Media Files Imported Correctly'),
        ),
    ]
