# Generated by Django 3.2.18 on 2024-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0047_uploadedarchive_mediafiles_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilesforidentification',
            name='paired_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
