# Generated by Django 3.2.18 on 2024-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0048_mediafilesforidentification_paired_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedarchive",
            name="earliest_captured_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Earliest Captured at"),
        ),
        migrations.AddField(
            model_name="uploadedarchive",
            name="latest_captured_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Latest Captured at"),
        ),
    ]
