# Generated by Django 3.2.18 on 2024-05-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0049_auto_20240425_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedarchive",
            name="status_message",
            field=models.CharField(blank=True, default="", max_length=2047),
        ),
    ]
