# Generated by Django 3.2.18 on 2024-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0050_uploadedarchive_status_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualidentity",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                default="U",
                max_length=2,
            ),
        ),
    ]
