# Generated by Django 3.2.18 on 2024-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0051_individualidentity_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='orientation',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('N', 'None')], default='N', max_length=2),
        ),
    ]
