# Generated by Django 3.2.18 on 2024-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0052_mediafile_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualidentity',
            name='coat_type',
            field=models.CharField(choices=[('S', 'Spots'), ('M', 'Marble'), ('U', 'Unknown')], default='U', max_length=2),
        ),
    ]
