# Generated by Django 3.2.18 on 2024-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0053_individualidentity_coat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualidentity',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
