# Generated by Django 3.2.18 on 2024-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0054_individualidentity_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedarchive',
            name='status_message',
            field=models.TextField(blank=True),
        ),
    ]
