# Generated by Django 3.2.18 on 2024-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0055_alter_uploadedarchive_status_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedarchive",
            name="taxon_for_identification_on_upload",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
