# Generated by Django 3.2.18 on 2024-05-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0056_uploadedarchive_taxon_for_identification_on_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedarchive',
            old_name='taxon_for_identification_on_upload',
            new_name='taxon_for_identification_at_upload',
        ),
    ]
