# Generated by Django 3.2.18 on 2024-05-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0059_auto_20240517_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='identification_init_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
