# Generated by Django 3.2.18 on 2024-06-06 20:17

import caidapp.model_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0060_alter_workgroup_identification_init_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="hash",
            field=models.CharField(default=caidapp.model_tools.random_string8, max_length=50),
        ),
    ]
