# Generated by Django 3.2.18 on 2024-06-07 07:28

import caidapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0061_location_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="hash",
            field=models.CharField(default=caidapp.models.get_hash8, max_length=50),
        ),
    ]
