# Generated by Django 3.2.18 on 2024-06-13 21:00

import caidapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0062_alter_location_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualidentity",
            name="hash",
            field=models.CharField(default=caidapp.models.get_hash8, max_length=50),
        ),
    ]
