# Generated by Django 3.2.18 on 2024-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0063_individualidentity_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualidentity",
            name="hash",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
