# Generated by Django 3.2.18 on 2024-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0065_auto_20240627_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarchive',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
