# Generated by Django 3.2.18 on 2024-08-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0066_uploadedarchive_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.taxon",
            ),
        ),
    ]
