# Generated by Django 3.2.18 on 2024-08-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0067_taxon_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedarchive",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
