# Generated by Django 3.2.18 on 2024-08-06 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0068_alter_uploadedarchive_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="predicted_taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predicted_taxon",
                to="caidapp.taxon",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="predicted_taxon_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
