# Generated by Django 3.2.18 on 2024-08-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0070_rename_taxon_overviewed_at_mediafile_taxon_verified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='taxon_overviewed',
            new_name='taxon_verified',
        ),
    ]
