# Generated by Django 3.2.18 on 2024-08-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0072_alter_mediafile_taxon_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="taxon_verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Taxon verified at"),
        ),
    ]
