# Generated by Django 3.2.18 on 2024-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0073_alter_mediafile_taxon_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedarchive',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Created'), ('F', 'Failed'), ('TAIP', 'Taxon processing'), ('TAAI', 'Taxon AI done'), ('TAKN', 'Taxa known'), ('TV', 'Taxa verified'), ('IAIP', 'ID processing'), ('IAID', 'ID AI done')], default='C', max_length=255),
        ),
    ]
