# Generated by Django 3.2.18 on 2024-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0075_alter_uploadedarchive_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedarchive",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Created"),
                    ("F", "Failed"),
                    ("TAIP", "Taxon processing"),
                    ("TAID", "Taxon AI done"),
                    ("TKN", "Taxa known"),
                    ("TV", "Taxa verified"),
                    ("IAIP", "ID processing"),
                    ("IAID", "ID AI done"),
                ],
                default="C",
                max_length=255,
            ),
        ),
    ]
