# Generated by Django 3.2.18 on 2024-09-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0076_alter_uploadedarchive_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedarchive",
            old_name="status",
            new_name="taxon_status",
        ),
    ]
