# Generated by Django 3.2.18 on 2024-10-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0079_auto_20240927_1927"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_id", models.IntegerField(blank=True, null=True)),
                (
                    "uploaded_archive",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caidapp.uploadedarchive",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mediafile",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caidapp.sequence",
            ),
        ),
    ]
