# Generated by Django 3.2.18 on 2024-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0080_auto_20241016_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
