# Generated by Django 3.2.18 on 2024-11-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0081_mediafile_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualidentity",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth date"),
        ),
        migrations.AddField(
            model_name="individualidentity",
            name="death_date",
            field=models.DateField(blank=True, null=True, verbose_name="Death date"),
        ),
    ]
