# Generated by Django 3.2.18 on 2024-11-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0082_auto_20241118_0741"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediafileIdentificationSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("video_sequence_frame_super_id", models.IntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("paired_points", models.JSONField(blank=True, null=True)),
                (
                    "for_identification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_mediafiles",
                        to="caidapp.mediafilesforidentification",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="caidapp.individualidentity",
                    ),
                ),
                (
                    "mediafile",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="caidapp.mediafile"
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
    ]
