# Generated by Django 3.2.18 on 2024-11-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0085_identificationmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="caiduser",
            name="actual_model",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="caidapp.identificationmodel"
            ),
        ),
    ]
