# Generated by Django 3.2.18 on 2024-11-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0086_caiduser_actual_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caiduser',
            old_name='actual_model',
            new_name='identification_model',
        ),
    ]
