# Generated by Django 4.2.16 on 2024-12-10 11:50

import caidapp.model_tools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0088_uploadedarchive_files_at_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedarchive",
            name="import_error_spreadsheet",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=models.CharField(blank=True, default=caidapp.model_tools.get_output_dir, max_length=255),
            ),
        ),
    ]
