# Generated by Django 4.2.16 on 2024-12-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0089_uploadedarchive_import_error_spreadsheet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="Locality",
        ),
    ]
