# Generated by Django 4.2.16 on 2024-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0090_rename_location_locality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediafile',
            old_name='location',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='uploadedarchive',
            old_name='location_at_upload',
            new_name='locality_at_upload',
        ),
        migrations.RenameField(
            model_name='uploadedarchive',
            old_name='location_at_upload_object',
            new_name='locality_at_upload_object',
        ),
        migrations.RenameField(
            model_name='uploadedarchive',
            old_name='location_check_at',
            new_name='locality_check_at',
        ),
        # migrations.RemoveField(
        #     model_name='uploadedarchive',
        #     name='location_check_at',
        # ),
        # migrations.AddField(
        #     model_name='uploadedarchive',
        #     name='locality_check_at',
        #     field=models.DateTimeField(blank=True, null=True, verbose_name='Locality Check at'),
        # ),
    ]
