# Generated by Django 4.2.16 on 2024-12-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0092_alter_uploadedarchive_locality_check_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediafiles', to='caidapp.locality'),
        ),
    ]
