# Generated by Django 4.2.16 on 2025-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0095_mediafile_static_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualidentity",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
