# Generated by Django 4.2.16 on 2025-02-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0096_alter_individualidentity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='media_file_corrupted',
            field=models.BooleanField(default=False, verbose_name='Media file corrupted'),
        ),
    ]
