# Generated by Django 4.2.16 on 2025-02-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0097_mediafile_media_file_corrupted'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
