# Generated by Django 5.1.6 on 2025-02-21 19:17

import caidapp.models
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0100_animalobservation_orientation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "visible_name",
                    models.CharField(blank=True, default=caidapp.models.human_readable_hash, max_length=255),
                ),
                ("location", location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ("hash", models.CharField(default=caidapp.models.get_hash8, max_length=50)),
                ("note", models.TextField(blank=True, default="")),
            ],
        ),
    ]
