# Generated by Django 5.1.6 on 2025-02-27 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0101_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="locality",
            name="area",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="caidapp.area"
            ),
        ),
    ]
