# Generated by Django 5.1.6 on 2025-02-28 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0103_alter_mediafile_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="caidapp.taxon",
                verbose_name="Taxon",
            ),
        ),
    ]
