# Generated by Django 5.1.6 on 2025-02-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0104_alter_mediafile_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediafile",
            old_name="category",
            new_name="taxon",
        ),
    ]
