# Generated by Django 5.1.6 on 2025-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0106_workgroup_identification_init_model_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="caiduser",
            name="show_taxon_classification",
            field=models.BooleanField(default=True),
        ),
    ]
