# Generated by Django 5.1.6 on 2025-04-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0108_caiduser_show_wellcome_message_on_next_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='caiduser',
            name='default_taxon_for_identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caidapp.taxon'),
        ),
    ]
