# Generated by Django 5.1.6 on 2025-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0109_caiduser_default_taxon_for_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='used_for_init_identification',
            field=models.BooleanField(default=False, verbose_name='Used for init identification'),
        ),
    ]
