# Generated by Django 5.1.6 on 2025-07-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0119_workgroup_identification_scheduled_run_eta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workgroup',
            old_name='identification_scheduled_run_task_id',
            new_name='identification_scheduled_reid_task_id',
        ),
    ]
