# Generated by Django 5.1.6 on 2025-08-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0121_rename_identification_scheduled_run_eta_workgroup_identification_scheduled_reid_eta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workgroup',
            old_name='identification_scheduled_reid_eta',
            new_name='identification_scheduled_run_eta',
        ),
        migrations.RenameField(
            model_name='workgroup',
            old_name='identification_scheduled_reid_task_id',
            new_name='identification_scheduled_run_task_id',
        ),
    ]
