# Generated by Django 5.2.6 on 2025-09-26 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0126_auto_20250926_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalobservation",
            name="mediafile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="caidapp.mediafile"
            ),
        ),
    ]
