# Generated by Django 5.2.6 on 2025-09-26 19:22


# migration is bascally empty, because i forgot to add the code into the operations list


from django.db import migrations

# def forwards(apps, schema_editor):
#     MediaFile = apps.get_model("caidapp", "MediaFile")
#     AnimalObservation = apps.get_model("caidapp", "AnimalObservation")
#
#     db_alias = schema_editor.connection.alias
#     for mf in tqdm(MediaFile.objects.using(db_alias).all(), desc="Migrating MediaFile to AnimalObservation"):
#         obs = AnimalObservation.objects.using(db_alias).create(
#             mediafile=mf,
#             taxon=mf.taxon,
#             taxon_verified=mf.taxon_verified,
#             taxon_verified_at=mf.taxon_verified_at,
#             predicted_taxon=mf.predicted_taxon,
#             predicted_taxon_confidence=mf.predicted_taxon_confidence,
#             identity=mf.identity,
#             identity_is_representative=mf.identity_is_representative,
#             orientation=mf.orientation,
#             updated_by=mf.updated_by,
#             updated_at=mf.updated_at,
#             metadata_json=mf.metadata_json,
#         )
#
#         # get the bbox from metadata_json["detection_results"]
#         if mf.metadata_json and "detection_results" in mf.metadata_json:
#             try:
#                 dets = ast.literal_eval(mf.metadata_json["detection_results"])
#                 if dets:
#                     if len(dets) > 1:
#                         print(f"Warning: More than one ({len(dets)})" +
#                         "detection result for MediaFile {mf.id}, using the first one.")
#                     det = dets[0]
#                     x_min, y_min, x_max, y_max = det["bbox"]
#                     h, w = det["size"]
#                     obs.bbox_x_center = ((x_min + x_max) / 2) / w
#                     obs.bbox_y_center = ((y_min + y_max) / 2) / h
#                     obs.bbox_width = (x_max - x_min) / w
#                     obs.bbox_height = (y_max - y_min) / h
#                     obs.save()
#             except Exception as e:
#                 print(f"Cannot parse detection_results for MediaFile {mf.id}: {e}")
#
# def backwards(apps, schema_editor):
#     AnimalObservation = apps.get_model("caidapp", "AnimalObservation")
#     db_alias = schema_editor.connection.alias
#     AnimalObservation.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0127_alter_animalobservation_mediafile"),
    ]

    operations = []
