# Generated by Django 5.2.6 on 2025-09-27 10:25

import ast

from django.db import migrations
from tqdm import tqdm


def forwards(apps, schema_editor):
    """Migrate data from MediaFile to AnimalObservation."""
    MediaFile = apps.get_model("caidapp", "MediaFile")
    AnimalObservation = apps.get_model("caidapp", "AnimalObservation")
    Taxon = apps.get_model("caidapp", "Taxon")

    db_alias = schema_editor.connection.alias
    AnimalObservation.objects.using(db_alias).all().delete()
    mediafiles = MediaFile.objects.using(db_alias).all()
    total = mediafiles.count()

    for mf in tqdm(mediafiles.iterator(), total=total, desc="Migrating MediaFile to AnimalObservation"):

        # if detection exists, create one AnimalObservation per detection
        dets = []
        if mf.metadata_json and "detection_results" in mf.metadata_json:
            try:
                dets = ast.literal_eval(mf.metadata_json["detection_results"])
            except Exception as e:
                print(f"Cannot parse detection_results for MediaFile {mf.id}: {e}")

        if dets:
            for i, det in enumerate(dets):
                x_min, y_min, x_max, y_max = det["bbox"]
                h, w = det["size"]
                confidence = float(det["confidence"]) if "confidence" in det else None
                rename_taxon = {
                    "vehicle": "Vehicle",
                    "person": "Homo sapiens",
                    "animal": "Animalia",
                }

                taxon_det = None
                mapped = rename_taxon.get(det.get("class"))
                if mapped:
                    taxon_det, _ = Taxon.objects.using(db_alias).get_or_create(name=mapped)
                orientation_mapping = {"back": "B", "front": "F", "left": "F", "right": "R", "unknown": "U", None: "U"}
                orientation_det = orientation_mapping.get(det.get("orientation"))

                AnimalObservation.objects.using(db_alias).create(
                    mediafile=mf,
                    taxon=mf.taxon if i == 0 else None,
                    taxon_verified=mf.taxon_verified if i == 0 else False,
                    taxon_verified_at=mf.taxon_verified_at if i == 0 else None,
                    predicted_taxon=mf.predicted_taxon if i == 0 else taxon_det,
                    predicted_taxon_confidence=confidence,
                    identity=mf.identity if i == 0 else None,  # jen první observation zdědí identity?
                    identity_is_representative=mf.identity_is_representative if i == 0 else False,
                    orientation=mf.orientation if i == 0 else orientation_det,
                    updated_by=mf.updated_by if i == 0 else None,
                    updated_at=mf.updated_at if i == 0 else None,
                    metadata_json=mf.metadata_json,
                    bbox_x_center=((x_min + x_max) / 2) / w,
                    bbox_y_center=((y_min + y_max) / 2) / h,
                    bbox_width=(x_max - x_min) / w,
                    bbox_height=(y_max - y_min) / h,
                )
        else:
            # fallback – no detection bbox
            AnimalObservation.objects.using(db_alias).create(
                mediafile=mf,
                taxon=mf.taxon,
                taxon_verified=mf.taxon_verified,
                taxon_verified_at=mf.taxon_verified_at,
                predicted_taxon=mf.predicted_taxon,
                predicted_taxon_confidence=mf.predicted_taxon_confidence,
                identity=mf.identity,
                identity_is_representative=mf.identity_is_representative,
                orientation=mf.orientation,
                updated_by=mf.updated_by,
                updated_at=mf.updated_at,
                metadata_json=mf.metadata_json,
            )


def backwards(apps, schema_editor):
    """Delete all AnimalObservation entries."""
    AnimalObservation = apps.get_model("caidapp", "AnimalObservation")
    db_alias = schema_editor.connection.alias
    AnimalObservation.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0128_auto_20250926_2122"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
