# Generated by Django 5.2.7 on 2025-10-07 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0129_auto_20250927_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitysuggestionresult',
            name='workgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caidapp.workgroup'),
        ),
    ]
