# Generated by Django 5.2.7 on 2025-10-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0130_identitysuggestionresult_workgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identitysuggestionresult",
            name="user",
        ),
    ]
