# Generated by Django 5.2.7 on 2025-10-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0131_remove_identitysuggestionresult_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentitySuggestionResult',
            new_name='MergeIdentitySuggestionResult',
        ),
    ]
