# Generated by Django 5.2.7 on 2025-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0132_rename_identitysuggestionresult_mergeidentitysuggestionresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualidentity',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
