# Generated by Django 5.2.7 on 2025-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0133_alter_individualidentity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualidentity',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
