# Generated by Django 5.2.7 on 2025-10-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0134_alter_individualidentity_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualidentity",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="individualidentity",
            name="juv_code",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Juv. Code"),
        ),
    ]
