# Generated by Django 5.2.7 on 2025-11-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0135_alter_individualidentity_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="check_taxon_before_identification",
            field=models.BooleanField(default=True, verbose_name="Check taxon before identification"),
        ),
    ]
