# Generated by Django 5.2.7 on 2025-12-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0137_alter_workgroup_check_taxon_before_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarchive',
            name='is_for_identification',
            field=models.BooleanField(default=False),
        ),
    ]
