# Generated by Django 5.2.9 on 2025-12-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0138_uploadedarchive_is_for_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
    ]
