# Generated by Django 5.2.10 on 2026-01-30 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0139_remove_notification_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_workgroup_invitations', to='caidapp.caiduser')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workgroup_invitations', to='caidapp.caiduser')),
                ('target_workgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='caidapp.workgroup')),
            ],
            options={
                'unique_together': {('invited_user', 'target_workgroup')},
            },
        ),
    ]
