# Generated by Django 5.2.11 on 2026-02-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0140_workgroupinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="caiduser",
            name="show_reid",
            field=models.BooleanField(default=True),
        ),
    ]
