# Generated by Django 5.2.11 on 2026-02-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0141_caiduser_show_reid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caiduser",
            name="identification_model",
        ),
    ]
