# Generated by Django 5.2.11 on 2026-03-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0143_workgroup_detection_model_architecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecipient',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='caidapp.notification'),
        ),
    ]
