# Generated by Codex on 2026-03-19

from django.db import migrations


def _extract_rank_paired_points(raw_points, rank_index):
    if not isinstance(raw_points, (list, tuple)):
        return None
    if rank_index >= len(raw_points):
        return None
    return raw_points[rank_index]


def backfill_top_fields_to_suggestions(apps, schema_editor):
    MediafilesForIdentification = apps.get_model("caidapp", "MediafilesForIdentification")
    MediafileIdentificationSuggestion = apps.get_model("caidapp", "MediafileIdentificationSuggestion")
    MediaFile = apps.get_model("caidapp", "MediaFile")

    for mfi in MediafilesForIdentification.objects.all().iterator():
        if MediafileIdentificationSuggestion.objects.filter(for_identification_id=mfi.id).exists():
            continue

        rank_data = [
            (
                getattr(mfi, "top1mediafile_id", None),
                getattr(mfi, "top1score", None),
                getattr(mfi, "top1name", ""),
                0,
            ),
            (
                getattr(mfi, "top2mediafile_id", None),
                getattr(mfi, "top2score", None),
                getattr(mfi, "top2name", ""),
                1,
            ),
            (
                getattr(mfi, "top3mediafile_id", None),
                getattr(mfi, "top3score", None),
                getattr(mfi, "top3name", ""),
                2,
            ),
        ]

        suggestions_to_create = []
        for mediafile_id, score, name, rank_index in rank_data:
            if mediafile_id is None and score is None and not name:
                continue

            suggestion = MediafileIdentificationSuggestion(
                for_identification_id=mfi.id,
                mediafile_id=mediafile_id,
                score=score,
                name=name or "",
                paired_points=_extract_rank_paired_points(getattr(mfi, "paired_points", None), rank_index),
            )

            if mediafile_id is not None:
                try:
                    top_mediafile = MediaFile.objects.get(id=mediafile_id)
                    suggestion.identity_id = getattr(top_mediafile, "identity_id", None)
                except MediaFile.DoesNotExist:
                    suggestion.identity_id = None

            suggestions_to_create.append(suggestion)

        if suggestions_to_create:
            MediafileIdentificationSuggestion.objects.bulk_create(suggestions_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0144_alter_notificationrecipient_notification"),
    ]

    operations = [
        migrations.RunPython(backfill_top_fields_to_suggestions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top1mediafile",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top2mediafile",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top3mediafile",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top1score",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top2score",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top3score",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top1name",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top2name",
        ),
        migrations.RemoveField(
            model_name="mediafilesforidentification",
            name="top3name",
        ),
    ]
