# Generated by Codex on 2026-03-19

import caidapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0145_backfill_and_remove_mfi_top_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workgroup",
            name="identity_code_regex",
            field=models.CharField(
                blank=True,
                default="B\\d+",
                help_text="Regular expression used to detect identity code suggestions in identity names.",
                max_length=128,
                validators=[caidapp.models.validate_identity_code_regex],
            ),
        ),
    ]
