# Generated by Codex on 2026-04-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("caidapp", "0146_workgroup_identity_code_regex"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentificationOutlierSuggestionResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("message", models.TextField(blank=True, default="")),
                ("suggestions", models.JSONField(blank=True, default=list)),
                (
                    "workgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caidapp.workgroup",
                    ),
                ),
            ],
        ),
    ]
