# Generated by Django 5.2.11 on 2026-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0147_identificationoutliersuggestionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBoxSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
