# Generated by Django 5.2.11 on 2026-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caidapp', '0150_uploadedarchive_import_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedarchive',
            name='mediafiles_imported',
            field=models.BooleanField(default=False, verbose_name='Media Files Import Finished Correctly'),
        ),
    ]
