FROM nvcr.io/nvidia/pytorch:23.05-py3

# install linux dependencies
RUN apt-get update --yes && \
    # - apt-get upgrade is run to patch known vulnerabilities in apt-get packages as
    #   the ubuntu base image is rebuilt too seldom sometimes (less than once a month)
    # apt-get upgrade --yes && \
    apt-get install --yes --no-install-recommends \
    wget \
    git \
    ffmpeg \
    libsm6 \
    libxext6 \
    tesseract-ocr \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


# download weights into resources
RUN mkdir -p ~/resources && \
    wget http://ptak.felk.cvut.cz/plants/DanishFungiDataset/md_v5a.0.0.pt \
    -O /root/resources/md_v5a.0.0.pt

# call torchub to load model into cache
RUN python -c "import torch; torch.hub.load('ultralytics/yolov5', 'custom','/root/resources/md_v5a.0.0.pt', force_reload=True) and print('yolov5 loaded')"
RUN ls /root/resources

COPY ./src/taxon_worker/requirements.txt /taxon_worker/requirements.txt

# install python dependencies
ENV APP_DIR='/taxon_worker'
WORKDIR $APP_DIR
RUN pip install --no-cache-dir --upgrade pip build && \
    pip install --no-cache-dir --compile -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/* /var/tmp/*

RUN pip install pytz --upgrade
RUN pip install tzdata --upgrade

RUN pip install \
    opencv-python==4.5.5.64 \
    opencv-python-headless==4.5.5.64

RUN pip install timm==0.6.13



# expose ports and run application
WORKDIR $APP_DIR
CMD C_FORCE_ROOT=false celery -A worker.taxon_worker worker --pool threads --concurrency 1 --loglevel debug --queues taxon_worker
# CMD C_FORCE_ROOT=false celery -A worker worker --pool threads --concurrency 2 --loglevel info --queues taxon_worker
