FROM python:3.9.16-slim

COPY ./src/api/requirements.txt /api/requirements.txt
COPY ./src/api/start_dev.sh /api/start_dev.sh

# install python dependencies
ENV APP_DIR='/api'
WORKDIR $APP_DIR
RUN pip install --no-cache-dir --upgrade pip build && \
    pip install --no-cache-dir --compile -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/* /var/tmp/*

# expose ports and run application
WORKDIR $APP_DIR
ENV PYTHONUNBUFFERED=1
EXPOSE 8080
CMD bash ./start_dev.sh
