FROM nvcr.io/nvidia/pytorch:23.05-py3

COPY ./src/inference_worker/requirements.txt /inference_worker/requirements.txt

# install linux dependencies
RUN apt-get update --yes && \
    # - apt-get upgrade is run to patch known vulnerabilities in apt-get packages as
    #   the ubuntu base image is rebuilt too seldom sometimes (less than once a month)
    # apt-get upgrade --yes && \
    apt-get install --yes --no-install-recommends \
    wget \
    git \
    ffmpeg \
    libsm6 \
    libxext6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN pip install git+https://github.com/facebookresearch/segment-anything.git

# download weights into resources
RUN mkdir -p ~/resources && \
    wget http://ptak.felk.cvut.cz/plants/DanishFungiDataset/md_v5a.0.0.pt \
    -O /root/resources/md_v5a.0.0.pt

RUN ls /root/resources

# install python dependencies
ENV APP_DIR='/inference_worker'
WORKDIR $APP_DIR
RUN pip install --no-cache-dir --upgrade pip build && \
    pip install --no-cache-dir --compile -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/* /var/tmp/*

RUN pip install \
    opencv-python==4.8.0.74 \
    opencv-python-headless==4.8.0.74

RUN pip install pytz --upgrade
RUN pip install tzdata --upgrade

#RUN pip install \
#    opencv-python==4.5.5.64 \
#    opencv-python-headless==4.5.5.64

# expose ports and run application
WORKDIR $APP_DIR
CMD C_FORCE_ROOT=false celery -A worker.inference_worker worker --pool threads --loglevel info --queues inference_worker
