FROM nvcr.io/nvidia/pytorch:23.05-py3

COPY ./src/inference_worker/requirements.txt /inference_worker/requirements.txt

# install python dependencies
ENV APP_DIR='/inference_worker'
WORKDIR $APP_DIR
RUN pip install --no-cache-dir --upgrade pip build && \
    pip install --no-cache-dir --compile -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/* /var/tmp/*

RUN pip install pytz --upgrade
RUN pip install tzdata --upgrade

# expose ports and run application
WORKDIR $APP_DIR
CMD C_FORCE_ROOT=false celery -A worker.inference_worker worker --pool threads --loglevel info --queues inference_worker
